name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check files
        run: |
          test -f index.html

      - name: Build Docker image
        run: |
          docker build -t ergasia-maps .
