name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Fix Executable Permissions for ESLint, Prettier and Jest
        run: chmod +x ./node_modules/.bin/eslint ./node_modules/.bin/prettier ./node_modules/.bin/jest

      - name: Run Linting
        run: npm run lint

      - name: Run Formatting Check
        run: npm run format:check

      - name: Run Unit Tests
        run: npx jest validation.test.js
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - name: Check files
        run: test -f index.html

      - name: Build Docker image
        run: docker build -t ergasia-maps .